<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function backoffice_thinking_autolabel_eck_form_auto_entitylabel_settings_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    $path = \Drupal::request()->getpathInfo();
    $arg  = explode('/',$path);
    if ($arg[2] == 'eck') {
      $form['auto_entitylabel']['token_help']['#token_types'][] = $arg[5];
    }
  }

  /**
 * Implements hook_entity_type_alter().
 */
function backoffice_thinking_autolabel_eck_entity_type_alter(array &$entity_types)
{
  foreach ($entity_types as $entity_type) {
    if ($entity_type->getProvider() == 'eck' && !is_null($entity_type->getBundleOf())){
      $entity_type->setLinkTemplate('auto-label', $entity_type->getLinkTemplate('edit-form') . "/auto-label");
    }
  }
}