module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  auto_entitylabel: 0
  automated_cron: 0
  backoffice_thinking_artcl_pers_res_ct: 0
  backoffice_thinking_autolobal_eck: 0
  backoffice_thinking_basic_page_and_paragraphs: 0
  backoffice_thinking_callout_component_and_elements: 0
  backoffice_thinking_def_tax: 0
  backoffice_thinking_entity_enabling: 0
  backoffice_thinking_events: 0
  backoffice_thinking_initial_setup: 0
  backoffice_thinking_link_cards_comp_and_elmnts: 0
  backoffice_thinking_responsive_image_and_related: 0
  backoffice_thinking_simple_title_body_comp: 0
  backoffice_thinking_slideshow_comp_and_elem: 0
  backoffice_thinking_testimonials_comp_and_elmnts: 0
  backoffice_thinking_views_block_component: 0
  better_exposed_filters: 0
  better_normalizers: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_class: 0
  block_content: 0
  book: 0
  bootstrap_layouts: 0
  breakpoint: 0
  button_link: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_delete: 0
  config_direct_save: 0
  config_update: 0
  contact: 0
  context: 0
  context_ui: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  default_content: 0
  default_content_deploy: 0
  devel: 0
  devel_generate: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  eck: 0
  editor: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_class_formatter: 0
  entity_reference_display: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_group: 0
  field_layout: 0
  field_ui: 0
  file: 0
  file_entity: 0
  filter: 0
  focal_point: 0
  google_analytics: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  insert_view: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  module_filter: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_library: 0
  paragraphs_viewmode: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  recaptcha: 0
  recaptcha_v3: 0
  responsive_image: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  slick: 0
  slick_entityreference: 0
  smart_trim: 0
  structure_sync: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  user: 0
  view_mode_selector: 0
  views_infinite_scroll: 0
  views_ui: 0
  viewsreference: 0
  ds: 1
  pathauto: 1
  ds_extras: 2
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  bot_custom: 0
  adminimal_theme: 0
  adminimal_bot: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
